#

server {
	server_name clara
	listen 90
	root /Users/clballes/Desktop/web42/www
	index index.html
	allow_methods PUT
	autoindex on
	error_page 413 /404.html
	cgi_pass /Users/clballes/Desktop/web42/src/cgi-bin/cgi_script.py
}


server {
	server_name clara
	listen 90
	root /Users/clballes/Desktop/web42/www
	index index.html
	allow_methods PUT
	autoindex on
	error_page 413 /404.html
	cgi_pass /Users/clballes/Desktop/web42/src/cgi-bin/cgi_script.py
}